spring:
  datasource:
    url: jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:ingredients_db}
    username: ${PGUSER:postgres}
    password: ${PGPASSWORD:postgres}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true